[package]
name = "kraken"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = { version = "0.4", features = [ "serde-json" ] }  # '-' not '_'
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
